// <auto-generated />
namespace Calculo_Biorritmo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Dayslivingchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dayslivingchange));
        
        string IMigrationMetadata.Id
        {
            get { return "202104290953161_Days living change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
